#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CBTablones.Resource", IsApplication=true)]

namespace CBTablones
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05002d
			public const int LvTablones = 2131034157;
			
			// aapt resource value: 0x7f05002c
			public const int addContacto = 2131034156;
			
			// aapt resource value: 0x7f050020
			public const int btnAbrirLogReg = 2131034144;
			
			// aapt resource value: 0x7f050015
			public const int btnAceptar = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int btnCancelar = 2131034134;
			
			// aapt resource value: 0x7f05002e
			public const int btnCrearTablon = 2131034158;
			
			// aapt resource value: 0x7f05001d
			public const int btnLoginAceptar = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int btnPrincipalLogin = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int btnPrincipalRegistrar = 2131034143;
			
			// aapt resource value: 0x7f05002a
			public const int btnRegistrarEnviar = 2131034154;
			
			// aapt resource value: 0x7f05000b
			public const int btnSiguiente = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int btnTomarFoto = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int edAlias = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int edEMail = 2131034129;
			
			// aapt resource value: 0x7f05000f
			public const int edNombre = 2131034127;
			
			// aapt resource value: 0x7f05001b
			public const int etLoginApodo = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int etLoginPassword = 2131034140;
			
			// aapt resource value: 0x7f050022
			public const int etRegistrarEmail = 2131034146;
			
			// aapt resource value: 0x7f050028
			public const int etRegistrarEstado = 2131034152;
			
			// aapt resource value: 0x7f050021
			public const int etRegistrarNombre = 2131034145;
			
			// aapt resource value: 0x7f050024
			public const int etRegistrarPassword = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int etRegistrarRepPassword = 2131034149;
			
			// aapt resource value: 0x7f050029
			public const int etRegistrarServidor = 2131034153;
			
			// aapt resource value: 0x7f050023
			public const int etRegistrarUsuario = 2131034147;
			
			// aapt resource value: 0x7f050003
			public const int imageButton1 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int imageButton2 = 2131034117;
			
			// aapt resource value: 0x7f05000d
			public const int imageView1 = 2131034125;
			
			// aapt resource value: 0x7f050018
			public const int imgContacto = 2131034136;
			
			// aapt resource value: 0x7f050007
			public const int imgCorredor = 2131034119;
			
			// aapt resource value: 0x7f05001a
			public const int imgTablon = 2131034138;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout2 = 2131034114;
			
			// aapt resource value: 0x7f050014
			public const int linearLayout3 = 2131034132;
			
			// aapt resource value: 0x7f05000c
			public const int linearLayout5 = 2131034124;
			
			// aapt resource value: 0x7f050006
			public const int listView1 = 2131034118;
			
			// aapt resource value: 0x7f05002b
			public const int listViewTabContact = 2131034155;
			
			// aapt resource value: 0x7f050017
			public const int lvContactos = 2131034135;
			
			// aapt resource value: 0x7f050012
			public const int spCaducidad = 2131034130;
			
			// aapt resource value: 0x7f050026
			public const int spRegistrarCaducidad = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int spRegistrarVolatilidad = 2131034151;
			
			// aapt resource value: 0x7f050013
			public const int spVolatilidad = 2131034131;
			
			// aapt resource value: 0x7f05002f
			public const int textItem = 2131034159;
			
			// aapt resource value: 0x7f050001
			public const int textView1 = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int textView2 = 2131034116;
			
			// aapt resource value: 0x7f050019
			public const int tvAlias = 2131034137;
			
			// aapt resource value: 0x7f050009
			public const int tvApodo = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int tvDorsal = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int tvNombre = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddParticipantes = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddParticipantesItemLo = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CrearTablon = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FormContactoLo = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ListaContactoLo = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ListaContactosItemLo = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ListaTablonesItemLo = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int LoginLo = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int LogRegLo = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Main = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int RegistrarLo = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int TabContactos = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int TabTablones = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int TextViewItemLo = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040007
			public const int aceptar = 2130968583;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f04000b
			public const int btnlogin = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int btnregistrar = 2130968588;
			
			// aapt resource value: 0x7f040005
			public const int caducidad = 2130968581;
			
			// aapt resource value: 0x7f040008
			public const int cancelar = 2130968584;
			
			// aapt resource value: 0x7f040003
			public const int edAlias = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int edEMail = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int edNombre = 2130968578;
			
			// aapt resource value: 0x7f040013
			public const int email = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int enviar = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int estado = 2130968593;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int mostrar_contacto = 2130968585;
			
			// aapt resource value: 0x7f04000f
			public const int nombre = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int password = 2130968590;
			
			// aapt resource value: 0x7f040010
			public const int repetirpassword = 2130968592;
			
			// aapt resource value: 0x7f040014
			public const int servidor = 2130968596;
			
			// aapt resource value: 0x7f04000a
			public const int tomar_fotos = 2130968586;
			
			// aapt resource value: 0x7f04000d
			public const int usuario = 2130968589;
			
			// aapt resource value: 0x7f040006
			public const int volatilidad = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
